imports:
    - { resource: parameters.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        cssrewrite: ~

    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
            filters:
                - lessphp
                - cssrewrite
            output: css/bootstrap.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
            output: js/bootstrap.js
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
            output: js/jquery.js
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

braincrafted_bootstrap:
    assets_dir: %kernel.root_dir%/../vendor/twitter/bootstrap
    auto_configure:
        twig: false
    less_filter: lessphp

fabex_tpb_best_torrent:
    uri: %uri_torrent%

fabex_sub_title_provider:
    providers:
        betaserie: true
        addicted: true
        opensubtitle: true
