services:
    fabex_app.manager.serie:
        class: null

    fabex_app.provider.torrent:
        class: Fabex\Bundle\AppBundle\Provider\Torrent\TorrentChainProvider

    fabex_app.provider.subtitle:
        class: Fabex\Bundle\AppBundle\Provider\Subtitle\SubtitleChainProvider